### ISSUE TITLE
docker: invalid publish opts format (should be name=value but got 'HOST_PORT:8000')

### ISSUE THREAD

**Issue by mdinata** [neuralet/smart-social-distancing#13]
Hi, i am new to docker and follow exactly as per the instruction 
$ sudo docker run -it --runtime nvidia --privileged -p HOST_PORT:8000 -v "$PWD/data":/data neuralet/smart-social-distancing:latest-jetson-nano
here's that i got
docker: invalid publish opts format (should be name=value but got 'HOST_PORT:8000')

please advise what i may probably miss

thank you

**Comment by mhsekhavat** [comment]
Hi @mdinata ,

Please replace `HOST_PORT` with the port number you would like to serve your application on. You can use 8000, for example, and run:

`sudo docker run -it --runtime nvidia --privileged -p 8000:8000 -v "$PWD/data":/data`

Then, you would open `http://localhost:8000` in your browser to see the UI.

**Comment by mdinata** [comment]
Thanks for the prompt feedback this case is solved.
Next error prompted. ImportError: libnvinfer.so.6: cannot open shared object file: No such file or directory. 
is it because this demo will run only on Jetpack 4.3, or is there any other way to do than Jetpack 4.3 fresh install.
Sorry different topic than the subject, appreciate your comment before i close this issue

**Comment by mhejrati** [comment]
Hi @mdinata 

Can you please provide details on what hardware and software you are running this on? Is it jetson-nano that is booted with jetpack 4.3?

**Comment by mdinata** [comment]
hi @mhejrati , my jetson is running on Jetpack 4.2.2. I guess that's the main problem of the last error. Thanks for the reply, i will close this issue
