### ISSUE TITLE
Import error for Detector

### ISSUE THREAD

**Issue by ajay443** [neuralet/smart-social-distancing#27]
I am trying to run Smart Distance on Jetson TX2, facing below issue. Please advice. Thank you. 

Env - 
1. Jetson Tx2 
2. Jetpack 4.3
3. CUDA 10.2

Steps to reproduce - 
1.  Follow all instructions for Jetson Tx2. 
2. Run below Docker command. 

```
docker run -it --runtime nvidia --privileged -p HOST_PORT:8000 -v "$PWD/data":/repo/data neuralet/smart-social-distancing:latest-jetson-nano
```

Output - 

![image](https://user-images.githubusercontent.com/2877819/86699082-7d56c800-bfd5-11ea-8aeb-b20374a59c09.png)
![image](https://user-images.githubusercontent.com/2877819/86700252-9449ea00-bfd6-11ea-9420-c9771ef2610b.png)

Expected - 
Live feed with smart distance for the video present in `data` folder
I also tried to correct the Download path, as per this [PR](https://github.com/neuralet/smart-social-distancing/pull/26)

**Comment by JsonSadler** [comment]
Hi, 
I could not reproduce this, and one big question for me is why your Cuda is 10.2 if you are using Jetpack 4.3?

**Comment by JsonSadler** [comment]
@ajay443 Can you test removing your previous docker images and in following the instructions, avoid building the image? If you skip the second step, 3'd step automatically pulls the docker from docker hub. Just one to check if this works or not.

**Comment by JsonSadler** [comment]
Make sure you are not using Jetpack 4.4 as it is not supported:
[https://github.com/neuralet/neuralet/issues/72](https://github.com/neuralet/neuralet/issues/72)

**Comment by ajay443** [comment]
Thank you. Yes the problem is related to [neuralet/neuralet#72](https://github.com/neuralet/neuralet/issues/72). Closing this issue as a duplicate to  [neuralet/neuralet#72](https://github.com/neuralet/neuralet/issues/72). 

I kind of overlooked the Jetpack version, thank you again.

**Comment by JsonSadler** [comment]
@ajay443 YW :)
