### ISSUE TITLE
How to use PI camera V2.0 as a video input?

### ISSUE THREAD

**Issue by mhaboali** [neuralet/smart-social-distancing#28]
Thanks for such a great and useful project.

Recently, I've been trying to test it with my PI camera V2.0(CSI-Camera) on Jetson Nano with JetPack 4.3, Ubuntu 18.04, and CUDA 10.0. 

I modified the Dockerfile of Nano you offer to disable running the command. Then I tried to run the gstreamer command inside the container but I got this error as shown here:

![image](https://user-images.githubusercontent.com/29764281/86848840-05f56700-c0af-11ea-830a-a9ae2f635699.png)

And the same command works on the same machine outside the docker container.

Could you help me to get it running with this CSI-Camera?

**Comment by mdegans** [comment]
I believe you must pass through the Argus socket. So add the following to your docker run:

```
-v /tmp/argus_socket:/tmp/argus_socket
```
You may also have to do the same with `/tmp/camsock` and `nvscsock`. I'm not certain but `--runtime nvidia` may bind mount all of this automatically.

**Comment by mhaboali** [comment]
Thanks a lot @mdegans 

Now it works by adding the argus_socket folder 🚀

**Comment by mhaboali** [comment]
I added some code in the core.py file to read the CSI camera instead of USB or video inputs and I've tested it and it worked as shown below. Should I create a pull request for that?

**Comment by mhejrati** [comment]
Yes, that would be very much appreciated @mhaboali

**Comment by mhaboali** [comment]
Hi sorry for the delay, I just got a time to create the PR.

Here's the pull request https://github.com/neuralet/smart-social-distancing/pull/34
