### ISSUE TITLE
ahmet@ahmet-desktop:~/smart-social-distancing$ docker run -it --runtime nvidia --privileged -p 8000:8000 -v "$PWD/data":/repo/data neuralet/smart-social-distancing:latest-jetson-nano docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown. ERRO[0001] error waiting for container: context canceled 

### ISSUE THREAD

**Issue by AhmetEnesYalcinkaya** [neuralet/smart-social-distancing#47]
Please help me ? I didnt understand how I solve it ?

**Comment by AhmetEnesYalcinkaya** [comment]
![Screenshot from 2020-08-01 22-01-41](https://user-images.githubusercontent.com/39588954/89108667-d7b33f00-d442-11ea-8486-1a3945d5f82a.png)

**Comment by mats-claassen** [comment]
Hi @AhmetEnesYalcinkaya are you running that on a Jetson Nano? If so, I think it seems the error is related to a wrong installation of NVIDIA drivers or the container toolkit. How did you flash the Nano?

**Comment by AhmetEnesYalcinkaya** [comment]
Yes I running on jetson nano. I installed properly docker.  I dont know what do you mean How did you flash the Nano?

**Comment by mats-claassen** [comment]
Yes, currently you need JetPack 4.3. Jetpack 4.4 is not supported yet. [This thread](https://github.com/neuralet/neuralet/issues/129) has more info on it

**Comment by renzodgc** [comment]
Hey, we just got around checking these old issues, sorry about the delay.

We still don't support JetPack 4.4 sadly.

I am closing this issue as it has been documented in #119
