### ISSUE TITLE
Lag of 20 seconds when input feed is from IP Camera

### ISSUE THREAD

**Issue by codebugged** [neuralet/smart-social-distancing#50]
Dear @mhejrati @mdegans 

The problem is that inference is working fine on Logitech webcam but on using IP cam through RTPS protocol, there is lag of 20 seconds. I want to over come that. Please help.

**Comment by renzodgc** [comment]
Hey, we just got around checking these old issues, sorry about the delay.

A strong delay like that may have been tied to some issue that was solved before. Although there is still a significant delay between the events of:
- An RTSP camera filming real-time
- Those frames being stored in the camera
- The processor consuming from the stream and processing its frames
- The gstreamer logger saving the video into a 5s file in the playlist
- The frontend downloading said file through HTTP or HTTPS

Of that lengthy process the first steps of the pipeline are strongly linked to the camera's hardware, the middle part is tied to the processor and the latter to the postprocessor video logger and the frontend downloading said files.

There's definitely room for improvement in the last two steps, although a noticeably long delay will still happen between the events.

Unfortunately improving this is not under the current development scope, as we are focusing more on the analytics generation and multicamera support than in video feed logging and video streaming.

That being said, any contribution regarding improving the gstreamer video_logger performance is welcome. I'll close this issue in a week.
