### ISSUE TITLE
Pedestrian plot and environment score plot: yet to be implemented?

### ISSUE THREAD

**Issue by tychotdeback** [neuralet/smart-social-distancing#54]
The tutorial page (https://neuralet.com/docs/tutorials/smart-social-distancing/) mentions the output view, and presents two nice analytic graphs: the pedestrian plot and the environment score plot. Using the newest version of the master branch on a jetson nano with jetpack 4.3 I see the video stream with detections and the birds eye view, yet I do not see the pedestrian and environment plots. Are they yet to be implemented, or am I perhaps missing something? Any hints would be greatly appreciated! 

Edit: In #25 I see a picture of the plot graph, strange, it is not displaying for me.

**Comment by mats-claassen** [comment]
Hi @tychotdeback did you run the frontend on the Jetson Nano or on another device. For me it works fine on master branch when starting the frontend on my computer and setting the correct IP and port in the `Processor` section of `config-frontend.ini`

**Comment by renzodgc** [comment]
Hey, we just got around checking these old issues, sorry about the delay.

The project has changed significantly in terms of the logged analytics, and the old frontend has been deprecated for a newer one https://www.beta.lanthorn.ai/, there's information in the README.md regarding it.

I'm closing this issue as it is not relevant anymore. But analytics and metrics should work correctly in the current version :)
